/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package digishop;

/**
 *
 * @author Shubh
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class Mobile extends javax.swing.JFrame {

    /**
     * Creates new form Mobile
     */
    public Mobile() {
        initComponents();
    }

    Connection con;
    PreparedStatement ps;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mobTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        Q1 = new javax.swing.JTextField();
        Q2 = new javax.swing.JTextField();
        Q3 = new javax.swing.JTextField();
        Q4 = new javax.swing.JTextField();
        Q5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("DigiShop");

        jLabel2.setText("User Id:");

        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mobTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mobTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Company", "Price", "Available Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mobTable.setRowHeight(40);
        jScrollPane1.setViewportView(mobTable);

        jLabel3.setText("Select Quantity");

        jButton3.setText("Load items");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Buy");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Buy");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Buy");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Buy");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Buy");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        Q1.setText("1");

        Q2.setText("1");

        Q3.setText("1");

        Q4.setText("1");

        Q5.setText("1");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shubh\\Downloads\\mobileimg.jpg")); // NOI18N

        jButton4.setText("My Orders");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Q4, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(Q3)
                                    .addComponent(Q2)
                                    .addComponent(Q1)
                                    .addComponent(Q5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user)
                            .addComponent(jButton1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton4)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(Q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(Q2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(Q3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(Q4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(Q5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(48, 48, 48)
                .addComponent(jButton3)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login lgpg = new Login();
        lgpg.setVisible(true);
        lgpg.pack();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/digishop?user=root&password=Asus14789");
            ps = con.prepareStatement("select Name, Company, Price, Quantity from mobile");
            ResultSet rs = ps.executeQuery();
            mobTable.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(Mobile.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
//        JOptionPane.showMessageDialog(this, "Logged in successfully!");        
        int q1 = Integer.parseInt(Q1.getText());
        int q=100;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/digishop?user=root&password=Asus14789");
            ps = con.prepareStatement("select Quantity from mobile where mobid=1");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                q = Integer.parseInt(rs.getString("Quantity"));
            }
            con.close();
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(Mobile.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(q>=q1)
        {
            String dbName = "";
            String dbCompany = "";
            int dbPrice = 0;
            int dbQuantity = 0;
            try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/digishop?user=root&password=Asus14789");
            ps = con.prepareStatement("select Name, Company, Price, Quantity from mobile where mobid=1");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                dbName = rs.getString("Name");
                dbCompany = rs.getString("Company");
                dbPrice = Integer.parseInt(rs.getString("Price"))*q1;
                dbQuantity = Integer.parseInt(rs.getString("Quantity"));
            }
            ps = con.prepareStatement("insert into orders(userId, prodname, price, quant) values(?,?,?,?)");
            ps.setInt(1, Integer.parseInt(user.getText()));
            ps.setString(2, dbName);
            ps.setInt(3, dbPrice);
            ps.setInt(4, q1);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully purchased "+q1+" "+dbName+"(s) for Rupees "+dbPrice);
            dbQuantity = dbQuantity-q1;
            ps = con.prepareStatement("update mobile set Quantity = ? where(mobid = 1)");
            ps.setInt(1, dbQuantity);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Mobile.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else{
            JOptionPane.showMessageDialog(this, "Not enough quantity available. Try again later");
        }       
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int q1 = Integer.parseInt(Q5.getText());
        int q=100;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/digishop?user=root&password=Asus14789");
            ps = con.prepareStatement("select Quantity from mobile where mobid=5");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                q = Integer.parseInt(rs.getString("Quantity"));
            }
            con.close();
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(Mobile.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(q>=q1)
        {
            String dbName = "";
            String dbCompany = "";
            int dbPrice = 0;
            int dbQuantity = 0;
            try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/digishop?user=root&password=Asus14789");
            ps = con.prepareStatement("select Name, Company, Price, Quantity from mobile where mobid=5");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                dbName = rs.getString("Name");
                dbCompany = rs.getString("Company");
                dbPrice = Integer.parseInt(rs.getString("Price"))*q1;
                dbQuantity = Integer.parseInt(rs.getString("Quantity"));
            }
            ps = con.prepareStatement("insert into orders(userId, prodname, price, quant) values(?,?,?,?)");
            ps.setInt(1, Integer.parseInt(user.getText()));
            ps.setString(2, dbName);
            ps.setInt(3, dbPrice);
            ps.setInt(4, q1);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully purchased "+q1+" "+dbName+"(s) for Rupees "+dbPrice);
            dbQuantity = dbQuantity-q1;
            ps = con.prepareStatement("update mobile set Quantity = ? where(mobid = 5)");
            ps.setInt(1, dbQuantity);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Mobile.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else{
            JOptionPane.showMessageDialog(this, "Not enough quantity available. Try again later");
        }       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int q1 = Integer.parseInt(Q2.getText());
        int q=100;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/digishop?user=root&password=Asus14789");
            ps = con.prepareStatement("select Quantity from mobile where mobid=2");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                q = Integer.parseInt(rs.getString("Quantity"));
            }
            con.close();
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(Mobile.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(q>=q1)
        {
            String dbName = "";
            String dbCompany = "";
            int dbPrice = 0;
            int dbQuantity = 0;
            try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/digishop?user=root&password=Asus14789");
            ps = con.prepareStatement("select Name, Company, Price, Quantity from mobile where mobid=2");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                dbName = rs.getString("Name");
                dbCompany = rs.getString("Company");
                dbPrice = Integer.parseInt(rs.getString("Price"))*q1;
                dbQuantity = Integer.parseInt(rs.getString("Quantity"));
            }
            ps = con.prepareStatement("insert into orders(userId, prodname, price, quant) values(?,?,?,?)");
            ps.setInt(1, Integer.parseInt(user.getText()));
            ps.setString(2, dbName);
            ps.setInt(3, dbPrice);
            ps.setInt(4, q1);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully purchased "+q1+" "+dbName+"(s) for Rupees "+dbPrice);
            dbQuantity = dbQuantity-q1;
            ps = con.prepareStatement("update mobile set Quantity = ? where(mobid = 2)");
            ps.setInt(1, dbQuantity);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Mobile.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else{
            JOptionPane.showMessageDialog(this, "Not enough quantity available. Try again later");
        }       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int q1 = Integer.parseInt(Q3.getText());
        int q=100;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/digishop?user=root&password=Asus14789");
            ps = con.prepareStatement("select Quantity from mobile where mobid=3");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                q = Integer.parseInt(rs.getString("Quantity"));
            }
            con.close();
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(Mobile.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(q>=q1)
        {
            String dbName = "";
            String dbCompany = "";
            int dbPrice = 0;
            int dbQuantity = 0;
            try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/digishop?user=root&password=Asus14789");
            ps = con.prepareStatement("select Name, Company, Price, Quantity from mobile where mobid=3");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                dbName = rs.getString("Name");
                dbCompany = rs.getString("Company");
                dbPrice = Integer.parseInt(rs.getString("Price"))*q1;
                dbQuantity = Integer.parseInt(rs.getString("Quantity"));
            }
            ps = con.prepareStatement("insert into orders(userId, prodname, price, quant) values(?,?,?,?)");
            ps.setInt(1, Integer.parseInt(user.getText()));
            ps.setString(2, dbName);
            ps.setInt(3, dbPrice);
            ps.setInt(4, q1);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully purchased "+q1+" "+dbName+"(s) for Rupees "+dbPrice);
            dbQuantity = dbQuantity-q1;
            ps = con.prepareStatement("update mobile set Quantity = ? where(mobid = 3)");
            ps.setInt(1, dbQuantity);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Mobile.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else{
            JOptionPane.showMessageDialog(this, "Not enough quantity available. Try again later");
        }       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int q1 = Integer.parseInt(Q4.getText());
        int q=100;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/digishop?user=root&password=Asus14789");
            ps = con.prepareStatement("select Quantity from mobile where mobid=4");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                q = Integer.parseInt(rs.getString("Quantity"));
            }
            con.close();
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(Mobile.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(q>=q1)
        {
            String dbName = "";
            String dbCompany = "";
            int dbPrice = 0;
            int dbQuantity = 0;
            try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/digishop?user=root&password=Asus14789");
            ps = con.prepareStatement("select Name, Company, Price, Quantity from mobile where mobid=4");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                dbName = rs.getString("Name");
                dbCompany = rs.getString("Company");
                dbPrice = Integer.parseInt(rs.getString("Price"))*q1;
                dbQuantity = Integer.parseInt(rs.getString("Quantity"));
            }
            ps = con.prepareStatement("insert into orders(userId, prodname, price, quant) values(?,?,?,?)");
            ps.setInt(1, Integer.parseInt(user.getText()));
            ps.setString(2, dbName);
            ps.setInt(3, dbPrice);
            ps.setInt(4, q1);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully purchased "+q1+" "+dbName+"(s) for Rupees "+dbPrice);
            dbQuantity = dbQuantity-q1;
            ps = con.prepareStatement("update mobile set Quantity = ? where(mobid = 4)");
            ps.setInt(1, dbQuantity);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Mobile.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else{
            JOptionPane.showMessageDialog(this, "Not enough quantity available. Try again later");
        }       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Morders mo = new Morders();
        mo.user.setText(String.valueOf(user.getText()));
        mo.setVisible(true);
        mo.pack();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        

        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mobile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Q1;
    private javax.swing.JTextField Q2;
    private javax.swing.JTextField Q3;
    private javax.swing.JTextField Q4;
    private javax.swing.JTextField Q5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mobTable;
    public javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
